ACCOUNTS = []
VERSION = "0.1.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
SIGNING_KEY = "GCU7KVTYEPCUZOQPJ6RLNWW64FS3IBHGZTEFWERO7ZZVDQYHMG7W5B6M"

WEB_AUTH_ENDPOINT = ""
TRANSFER_SERVER_SEP0024 = ""

[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
status = "test"
is_asset_anchored = false
anchor_asset_type = "fiat"
desc = "A test USDC issued by Circle."

[DOCUMENTATION]
ORG_NAME = "Shamba Records"
ORG_URL = "https://www.shambarecords.com"
ORG_DESCRIPTION = "Turning farm data into financial identity for emerging markets."
ORG_LOGO = "https://www.shambarecords.com/Logo/shamba.svg"
ORG_SUPPORT_EMAIL = "info@shambarecords.com"
