FROM golang:1.25-alpine

WORKDIR /app

# Install Node.js and npm for Redocly
RUN apk add --no-cache nodejs npm

# Install Go tools
RUN go install github.com/air-verse/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
