FROM node:20-alpine
RUN apk add --no-cache python3 make g++ linux-headers eudev-dev
RUN npm install -g npm@12.0.2
RUN npm config set allow-remote all
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
